version: '3.3'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./create-tweetler-db.sql:/docker-entrypoint-initdb.d/create-tweetler-db.sql
volumes:
  db:
    driver: local